services:
  db:
    secrets:
      - db_password
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_PASSWORD_FILE: "/run/secrets/db_password"

  api:
    secrets:
      - db_password
    environment:
      DB_PASSWORD: ""
      DB_PASSWORD_FILE: "/run/secrets/db_password"

secrets:
  db_password:
    file: ./secrets/db_password.txt